my:
  servers:
    - dev.bar.com
    - foo.bar.com
    - jiaobuchong.com
spring:
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 50
      keepAliveSeconds: 8
      queueCapacity: 1000
  redis:
    database: 0
    host: 172.16.60.12
    port: 6379
    password: cwkj0987
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0